### ISSUE TITLE
Support legacy Rubocop

### ISSUE THREAD

**Issue by mms-pl** [jsmecham/nova-rubocop#2]
Thanks for fixing bundler :)

However, the extension still doesn't work for me:

```
RuboCop[19:37:35.502000] Found RuboCop 0.51.0 (Bundled)

RuboCop[19:37:37.847000] invalid option: --no-display-cop-names
/Users/msapka/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/options.rb:19:in `parse'
/Users/msapka/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/cli.rb:27:in `run'
/Users/msapka/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/bin/rubocop:13:in `block in <top (required)>'
/Users/msapka/.rbenv/versions/2.3.8/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/Users/msapka/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/bin/rubocop:12:in `<top (required)>'
/Users/msapka/.rbenv/versions/2.3.8/bin/rubocop:22:in `load'
/Users/msapka/.rbenv/versions/2.3.8/bin/rubocop:22:in `<main>'
```

I'm 99% sure that this means Rubocop we are using is too old for this fancy option.

**Comment by jsmecham** [comment]
Eek. Good to know! Will add some checks for RuboCop version and support for this option.

**Comment by mms-pl** [comment]
Thank you :)

Since I'd love to use this plugin in my daily work, would be possible to specify any ETA? Like: days, weeks, next time I've got free afternoon?

**Comment by jsmecham** [comment]
Try now (in 0.3.1). I went ahead and reverted the change where I enabled that flag on the `rubocop` in favor of stripping it out manually.

**Comment by mms-pl** [comment]
The process runs, so yeah this is fixed. Thank you ;)

However, I now experience the same problem as in https://github.com/jsmecham/nova-eslint/issues/2

**Comment by mms-pl** [comment]
FYI: I've bumped Rubocop tp 0.80.0 in few of our repositories, and the errors are marked in editor.

**Comment by jsmecham** [comment]
Thanks for the update. I'm going to try stepping back through older versions of RuboCop to see if I can fix it for older versions, as well.

**Comment by martinstreicher** [comment]
I installed Nova and opened a Ruby project with a _.rubocop.yml_ and a _Gemfile_. However, Rubocop does not seem to be policing my changes as I edit the code and/or save the file. I have Rubocop 0.91.0.
